title: Alessa Afiqah Johar
logo: "/assets/aafiqah.png" 
description: >
  <br/>
  Mobile Developer
  <br/>
  <a href="mailto:alessajohar@gmail.com">
        <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white">
      </a>&nbsp;
      <a href="https://www.linkedin.com/in/alessaafiqahjohar/">
        <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white">
      </a>
      <a href="https://github.com/aafiqah">
        <img src="https://img.shields.io/badge/GitHub%20Pages-222222?style=for-the-badge&logo=GitHub%20Pages&logoColor=white">
      </a>
theme: jekyll-theme-minimal
