title: Alessa Afiqah Johar
logo: "/assets/aafiqah.png" 
description: >
  <h2>Mobile Developer<h2>
  <a href="mailto:alessajohar@gmail.com">
        <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white">
      </a>&nbsp;
      <a href="https://www.linkedin.com/in/alessaafiqahjohar/">
        <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white">
      </a>
      <a href="https://github.com/aafiqah">
        <img src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white">
      </a>
      <a href="/assets/Alessa Afiqah Johar-Resume-mobile developer.pdf">
        <img src="https://img.shields.io/badge/PDF-000000?style=for-the-badge&logo=About.me&logoColor=white">
      </a>
theme: jekyll-theme-minimal
